const initialState = {
  producers: [
    {
      id: 1,
      name: "José da Silva",
      cpf: "111.222.333-44",
      city: "São Paulo",
      state: "SP",
      farmTotal: 1000,
      arableLand: 500,
      vegetationArea: 300,
      crops: "Soja, Milho",
    },
    {
      id: 2,
      name: "Maria Fernandes",
      cpf: "222.333.444-55",
      city: "Rio de Janeiro",
      state: "RJ",
      farmTotal: 2000,
      arableLand: 1000,
      vegetationArea: 500,
      crops: "Café,Cana de Açúcar",
    },
    {
      id: 3,
      name: "Pedro Souza",
      cpf: "333.444.555-66",
      city: "Belo Horizonte",
      state: "MG",
      farmTotal: 3000,
      arableLand: 1500,
      vegetationArea: 1000,
      crops: "Algodão",
    },
    {
      id: 4,
      name: "Julia Oliveira",
      cpf: "444.555.666-77",
      city: "Porto Alegre",
      state: "RS",
      farmTotal: 2500,
      arableLand: 1800,
      vegetationArea: 700,
      crops: "Milho",
    },
    {
      id: 5,
      name: "Lucas Fernandes",
      cpf: "555.666.777-88",
      city: "Curitiba",
      state: "PR",
      farmTotal: 4000,
      arableLand: 2000,
      vegetationArea: 1500,
      crops: "Soja,Café",
    },
    {
      id: 6,
      name: "Amanda Costa",
      cpf: "666.777.888-99",
      city: "Fortaleza",
      state: "CE",
      farmTotal: 500,
      arableLand: 200,
      vegetationArea: 100,
      crops: "Algodão",
    },
    {
      id: 7,
      name: "Ricardo Almeida",
      cpf: "777.888.999-00",
      city: "Salvador",
      state: "BA",
      farmTotal: 1200,
      arableLand: 800,
      vegetationArea: 300,
      crops: "Cana de Açúcar",
    },
    {
      id: 8,
      name: "Sofia Santos",
      cpf: "888.999.000-11",
      city: "Recife",
      state: "PE",
      farmTotal: 1800,
      arableLand: 1000,
      vegetationArea: 600,
      crops: "Cana de Açúcar,Soja",
    },
    {
      id: 9,
      name: "Felipe Carvalho",
      cpf: "999.000.111-22",
      city: "Manaus",
      state: "AM",
      farmTotal: 700,
      arableLand: 500,
      vegetationArea: 150,
      crops: "Café,Soja",
    },
  ],
};

export default initialState;
